'use strict';
const $ = id => document.getElementById(id);
const MODELS = {
  entman:'Robert N. Entman',
  pan_kosicki:'Zhongdang Pan & Gerald M. Kosicki',
  gamson_modigliani:'William A. Gamson & Andre Modigliani',
  edelman:'Murray Edelman'
};
const STOPWORDS = new Set(`yang dan di ke dari untuk dengan pada adalah itu ini dalam sebagai oleh atau juga karena agar akan telah sudah belum tidak bisa dapat suatu sebuah para mereka kami kita ia dia hingga sampai antara terhadap terkait tentang namun tetapi serta menjadi pun lebih sangat saat ketika jika maka ada kepada tersebut setelah sebelum luar masih hanya kembali bagi melalui sejak tahun bulan hari secara seorang beberapa salah satu dua tiga empat lima enam tujuh delapan sembilan sepuluh kata menurut ujar mengatakan menyebut menjelaskan menyatakan pihak hal atas bawah lalu kemudian yakni yaitu bahwa media berita dilakukan melakukan merupakan soal kasus orang warga pemerintah daerah kota kabupaten indonesia hari`.split(/\s+/));
const CAUSE_MARKERS=['karena','akibat','sebab','disebabkan','dipicu','berawal','lantaran','sehingga','menyebabkan','berdampak','berujung','alasan','dilatarbelakangi'];
const MORAL_MARKERS=['harus','seharusnya','semestinya','wajib','penting','adil','tidak adil','melanggar','pelanggaran','benar','salah','layak','tidak layak','wajar','bertanggung jawab','hak','kewajiban','moral','etika','sesuai aturan','tidak sesuai','patut','tidak patut'];
const TREATMENT_MARKERS=['solusi','menyelesaikan','penyelesaian','meminta','mendorong','mengusulkan','menunda','menghentikan','melanjutkan','menindak','menetapkan','memutuskan','perlu','upaya','langkah','rekomendasi','jalan keluar','mediasi','negosiasi','proses hukum','pengadilan','dialog','evaluasi','meninjau','mencegah'];
const EVALUATIVE_WORDS=['keras','tegas','genting','serius','krusial','kontroversial','dramatis','ancaman','korban','nakal','ilegal','sengketa','konflik','gugatan','krisis','desak','menolak','mendukung','mengecam','memprotes','mempertahankan','merugikan','meresahkan','bermasalah','penting'];
let lastResult=null;

function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function norm(s){return String(s??'').replace(/\s+/g,' ').trim();}
function short(s,n=330){s=norm(s);return !s?'Tidak teridentifikasi dari data yang tersedia.':(s.length<=n?s:s.slice(0,n-1).trim()+'…');}
function setStatus(msg,kind='info'){const e=$('status');e.className=`status ${kind}`;e.textContent=msg;}
function clearStatus(){$('status').className='status hidden';$('status').textContent='';}
function splitSentences(text){return norm(text).split(/(?<=[.!?])\s+/).map(norm).filter(x=>x.length>=30);}
function tokens(text){return (String(text).toLowerCase().match(/[a-zà-öø-ÿ0-9-]{3,}/gi)||[]).map(x=>x.toLowerCase()).filter(x=>!STOPWORDS.has(x)&&!/^[0-9]+$/.test(x));}
function topTerms(text,n=15){const m=new Map();for(const t of tokens(text))m.set(t,(m.get(t)||0)+1);return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,n);}
function sentencesWith(sents,markers,limit=4){return sents.map((s,i)=>({s,i,h:markers.reduce((n,m)=>n+(s.toLowerCase().includes(m)?1:0),0)})).filter(x=>x.h).sort((a,b)=>b.h-a.h||a.i-b.i).slice(0,limit).map(x=>x.s);}
function evidence(items,empty='Tidak ditemukan secara eksplisit dalam teks.'){return items?.length?items.map(x=>short(x)):[empty];}
function common(article){const sents=splitSentences(article.text);return{sentences:sents,terms:topTerms(`${article.title||''} ${article.text}`,15),causes:sentencesWith(sents,CAUSE_MARKERS),morals:sentencesWith(sents,MORAL_MARKERS),treatments:sentencesWith(sents,TREATMENT_MARKERS),evaluative:sentencesWith(sents,EVALUATIVE_WORDS)};}
function dominantFrame(a){const terms=a.terms.slice(0,5).map(x=>x[0]);return terms.length?`Teks terutama mengarahkan perhatian pada ${terms.join(', ')}. Bagian awal dan pengulangan istilah menempatkan tema tersebut sebagai pusat persoalan.`:'Frame dominan belum dapat diidentifikasi secara memadai.';}
function guessSection(article){const hay=`${article.url||''} ${article.text.slice(0,5000)}`.toLowerCase();const mapping={hukum:['hukum','gugatan','pengadilan','putusan','pidana','perdata'],politik:['politik','pemilu','partai','dpr','pilkada','pemerintah'],ekonomi:['ekonomi','bisnis','pasar','keuangan','investasi'],kriminal:['kriminal','polisi','tersangka','penangkapan'],pendidikan:['pendidikan','sekolah','kampus','mahasiswa','pesantren'],sosial:['sosial','warga','masyarakat','komunitas']};let best=['tidak teridentifikasi',0];for(const [k,arr] of Object.entries(mapping)){const s=arr.reduce((n,w)=>n+(hay.split(w).length-1),0);if(s>best[1])best=[k,s];}return best[0];}
function analyzeEntman(article){const a=common(article);const def=a.sentences.slice(0,3);return{summary:dominantFrame(a),sections:[{title:'Define Problems — pendefinisian masalah',interpretation:'Judul dan bagian awal dipakai untuk membaca bagaimana media menentukan “apa masalahnya”.',evidence:evidence(def)},{title:'Diagnose Causes — penyebab/aktor penyebab',interpretation:'Kalimat dengan penanda sebab-akibat dipakai sebagai indikasi atribusi penyebab. Jika tidak ada bukti eksplisit, aplikasi tidak memaksakan penyebab.',evidence:evidence(a.causes)},{title:'Make Moral Judgment — penilaian moral',interpretation:'Bahasa normatif, hak, kewajiban, kepatutan, dan evaluasi dipakai sebagai petunjuk legitimasi atau delegitimasi tindakan.',evidence:evidence(a.morals)},{title:'Treatment Recommendation — arah penyelesaian',interpretation:'Kalimat yang mengandung solusi, tuntutan, keputusan, atau langkah tindak lanjut dipakai sebagai arah penyelesaian yang ditonjolkan.',evidence:evidence(a.treatments)}],conclusion:`Frame dominan terbaca melalui penonjolan istilah ${a.terms.slice(0,6).map(x=>x[0]).join(', ')||'pada judul dan lead'}. Kesimpulan ini adalah coding awal berbasis bukti tekstual.`};}
function analyzePan(article){const a=common(article),s=a.sentences,quotes=[...article.text.matchAll(/[“"]([^”"]{20,240})[”"]/g)].map(m=>m[1]);const low=article.text.toLowerCase();const wh={What:!!(article.title||s.length),Who:/\b(menurut|ujar|kata|pihak|warga|pemerintah|polisi|pengacara|ketua|kepala|bupati|gubernur)\b/i.test(low),When:/\b(senin|selasa|rabu|kamis|jumat|sabtu|minggu|20\d{2})\b/i.test(low),Where:/\b(di|dari|menuju)\s+[A-Z][A-Za-z.-]+/.test(article.text),Why:!!a.causes.length,How:!!a.treatments.length||/\b(dengan cara|melalui|mekanisme|proses)\b/i.test(low)};return{summary:dominantFrame(a),sections:[{title:'Sintaksis — cara fakta disusun',interpretation:`Headline: ${article.title||'tidak tersedia'}. Lead: ${short(s[0]||'')}. Kutipan langsung terdeteksi: ${quotes.length}.`,evidence:evidence(quotes.slice(0,3),'Tidak ditemukan kutipan langsung yang jelas.')},{title:'Skrip — cara fakta dikisahkan',interpretation:`5W+1H: ${Object.entries(wh).map(([k,v])=>`${k}: ${v?'ada':'belum terdeteksi'}`).join('; ')}.`,evidence:evidence(a.causes.slice(0,3),'Unsur sebab/why belum terdeteksi secara eksplisit.')},{title:'Tematik — cara fakta ditulis',interpretation:`Tema dominan: ${a.terms.slice(0,8).map(([w,c])=>`${w} (${c})`).join(', ')||'tidak teridentifikasi'}. Teks berisi ${s.length} kalimat yang dianalisis.`,evidence:evidence(s.slice(0,3))},{title:'Retoris — cara fakta ditekankan',interpretation:'Istilah evaluatif dan penekanan leksikal dipakai sebagai petunjuk retoris. Aplikasi tidak menafsirkan foto secara visual.',evidence:evidence(a.evaluative)}],conclusion:'Frame Pan & Kosicki dibaca melalui susunan headline/lead, struktur cerita, tema, dan penekanan retoris. Hasil ini adalah coding awal, bukan pengganti pembacaan kualitatif penuh.'};}
function analyzeGamson(article){const a=common(article),quotes=[...article.text.matchAll(/[“"]([^”"]{8,160})[”"]/g)].map(m=>m[1]),met=sentencesWith(a.sentences,['ibarat','bak ','laksana','umpama','seperti ','bagaikan'],3),ex=(article.paragraphs||[]).filter(p=>/\b(misalnya|contohnya|sebagai contoh|kasus)\b/i.test(p)).slice(0,3),core=a.terms.slice(0,6).map(x=>x[0]).join(', ')||'tidak teridentifikasi';return{summary:`Interpretative package yang paling mungkin berpusat pada: ${core}.`,sections:[{title:'Core Frame / gagasan sentral',interpretation:`Gagasan sentral diperkirakan berpusat pada ${core}.`,evidence:evidence(a.sentences.slice(0,3))},{title:'Framing Devices',interpretation:'Perangkat yang dicari: metaphors, exemplars, catchphrases, depictions, dan penekanan simbolik dalam teks.',evidence:evidence([...met,...ex,...quotes.slice(0,2),...a.evaluative.slice(0,2)].slice(0,6),'Perangkat framing eksplisit terbatas pada input ini.')},{title:'Reasoning Devices — Roots',interpretation:'Roots dibaca dari hubungan sebab-akibat yang membenarkan cara melihat isu.',evidence:evidence(a.causes)},{title:'Reasoning Devices — Appeal to Principle',interpretation:'Klaim moral/prinsip dibaca dari bahasa normatif yang digunakan sebagai pembenar.',evidence:evidence(a.morals)}],conclusion:'Paket framing dibentuk oleh gagasan sentral, simbol/frasa penonjol, serta alasan kausal dan normatif. Makna simbolik implisit tetap perlu diverifikasi peneliti.'};}
function analyzeEdelman(article){const a=common(article),cat=guessSection(article),terms=a.terms.slice(0,8).map(x=>x[0]).join(', ')||'tidak teridentifikasi';return{summary:`Realitas terutama dikategorisasikan dalam ranah ${cat}, dengan label dominan: ${terms}.`,sections:[{title:'Kategorisasi',interpretation:'Judul dan istilah dominan menyederhanakan realitas ke kategori tertentu dan menentukan sisi peristiwa yang paling mudah diingat.',evidence:evidence([article.title,...a.sentences.slice(0,2)].filter(Boolean))},{title:'Rubrikasi',interpretation:`Kategori yang diperkirakan dari URL/teks: ${cat}.`,evidence:evidence([`Domain: ${article.domain||'-'}`,`URL: ${article.url||'-'}`])},{title:'Kategorisasi dan ideologi',interpretation:'Aplikasi tidak menetapkan ideologi media secara otomatis. Ia hanya menandai bahwa pemilihan kategori dan label dapat mengarahkan perhatian pembaca.',evidence:evidence(a.evaluative.slice(0,4),'Tidak ada bahasa evaluatif kuat yang terdeteksi.')}],conclusion:'Dalam model Edelman, framing paling terlihat pada kategorisasi, rubrikasi, dan pelabelan. Implikasi ideologis harus diuji melalui perbandingan sumber dan konteks lain.'};}
function analyzeModel(model,article){return model==='pan_kosicki'?analyzePan(article):model==='gamson_modigliani'?analyzeGamson(article):model==='edelman'?analyzeEdelman(article):analyzeEntman(article);}

function extractActors(text){const matches=text.match(/\b[A-Z][A-Za-zÀ-ÖØ-öø-ÿ.'’-]{2,}(?:\s+[A-Z][A-Za-zÀ-ÖØ-öø-ÿ.'’-]{2,}){0,3}\b/g)||[];const bad=new Set(['Indonesia','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu']);const m=new Map();for(const x of matches){const n=norm(x);if(bad.has(n)||n.split(' ').length===1&&STOPWORDS.has(n.toLowerCase()))continue;m.set(n,(m.get(n)||0)+1);}return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5).map(x=>x[0]);}
function focusEvidence(article,focus){const f=tokens(focus).filter(x=>x.length>3);if(!f.length)return[];return splitSentences(article.text).map(s=>({s,h:f.reduce((n,w)=>n+(s.toLowerCase().includes(w)?1:0),0)})).filter(x=>x.h).sort((a,b)=>b.h-a.h).slice(0,5).map(x=>x.s);}
function evidenceStrength(article,a){let s=25;s+=Math.min(20,article.text.length/500);s+=Math.min(15,a.sentences.length/3);s+=Math.min(10,a.causes.length*3);s+=Math.min(10,a.morals.length*2);s+=Math.min(10,a.treatments.length*2);s+=Math.min(10,([...(article.text.matchAll(/[“"]/g))].length));return Math.max(0,Math.min(100,Math.round(s)));}
function buildQuick(article,analysis,focus){const a=common(article),actors=extractActors(article.text),strength=evidenceStrength(article,a),terms=a.terms.slice(0,6).map(x=>x[0]);const gaps=[];if(!a.causes.length)gaps.push('atribusi penyebab belum eksplisit');if(!a.morals.length)gaps.push('penilaian normatif terbatas');if(!a.treatments.length)gaps.push('arah solusi belum eksplisit');if(!/[“"]/.test(article.text))gaps.push('kutipan langsung tidak terdeteksi');return{strength,items:[['Inti frame',analysis.summary],['Aktor/entitas menonjol',actors.length?actors.join(', '):'Belum dapat diidentifikasi dengan cukup kuat.'],['Istilah paling ditonjolkan',terms.join(', ')||'Belum cukup data.'],['Pola sebab',a.causes[0]?short(a.causes[0],250):'Tidak ada atribusi sebab yang eksplisit.'],['Arah moral/evaluasi',a.morals[0]?short(a.morals[0],250):'Bahasa moral/normatif tidak menonjol.'],['Hal yang perlu dibaca hati-hati',gaps.length?gaps.join('; '):'Bukti tekstual relatif lengkap, tetapi konteks eksternal tetap perlu diverifikasi.']],focusEvidence:focusEvidence(article,focus)};}

async function readUrlWithJina(url){const u=norm(url);if(!/^https?:\/\//i.test(u))throw new Error('Alamat URL harus diawali http:// atau https://');const endpoint='https://r.jina.ai/'+u;const r=await fetch(endpoint,{method:'GET'});if(!r.ok)throw new Error(`Reader gagal membaca URL (HTTP ${r.status}).`);const raw=await r.text();const title=(raw.match(/^Title:\s*(.+)$/mi)||[])[1]||'';const published=(raw.match(/^Published Time:\s*(.+)$/mi)||[])[1]||'';let content=raw.replace(/^Title:.*$/mi,'').replace(/^URL Source:.*$/mi,'').replace(/^Published Time:.*$/mi,'').replace(/^Markdown Content:\s*/mi,'');content=content.replace(/!\[[^\]]*\]\([^)]*\)/g,' ').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/^#{1,6}\s+/gm,'').replace(/[*_`>#]/g,' ').replace(/\n{3,}/g,'\n\n').trim();if(content.length<180)throw new Error('Isi artikel tidak cukup terbaca otomatis. Tempel teks manual.');const domain=new URL(u).hostname;return{url:u,domain,title:norm(title),published:norm(published),author:'',section:'',text:content.slice(0,70000),paragraphs:content.split(/\n+/).map(norm).filter(x=>x.length>=30),method:'Jina Reader'};}
function manualArticle(text,title,url=''){const t=String(text||'').trim().slice(0,70000);return{url,domain:url?(()=>{try{return new URL(url).hostname}catch{return''}})():'',title:norm(title),published:'',author:'',section:'',text:t,paragraphs:t.split(/\n+/).map(norm).filter(x=>x.length>=30),method:'Teks manual'};}
function buildQuery(article,focus){const ft=tokens(focus).filter(x=>x.length>3).slice(0,6);const tt=topTerms(`${article.title} ${article.text}`,8).map(x=>x[0]);const q=[...new Set([...ft,...tt])].slice(0,7).join(' ');return q||article.title||'media framing';}
function overlapScore(title,query){const q=new Set(tokens(query));const t=new Set(tokens(title));if(!q.size)return 0;let n=0;for(const x of q)if(t.has(x))n++;return Math.round(100*n/q.size);}
function cleanTitle(x){return Array.isArray(x)?norm(x[0]||''):norm(x||'');}
function yearFromCrossref(w){const p=w['published-print']||w['published-online']||w.published||w.issued;return p?.['date-parts']?.[0]?.[0]||'';}
function authorFromCrossref(w){return (w.author||[]).slice(0,3).map(a=>[a.given,a.family].filter(Boolean).join(' ')).join(', ')+(w.author?.length>3?' et al.':'');}
async function searchCrossref(query){const u=`https://api.crossref.org/works?query.bibliographic=${encodeURIComponent(query)}&rows=8&sort=relevance`;
 const r=await fetch(u);if(!r.ok)throw new Error('Crossref tidak merespons.');const j=await r.json();return (j.message?.items||[]).map(w=>({kind:'Crossref',title:cleanTitle(w.title),url:w.URL||(`https://doi.org/${w.DOI}`),doi:w.DOI||'',authors:authorFromCrossref(w),year:yearFromCrossref(w),container:cleanTitle(w['container-title']),score:overlapScore(cleanTitle(w.title),query)})).filter(x=>x.title).sort((a,b)=>b.score-a.score).slice(0,6);}
async function searchDataCite(query){const u=`https://api.datacite.org/dois?query=${encodeURIComponent(query)}&page%5Bsize%5D=8&sort=relevance`;const r=await fetch(u);if(!r.ok)throw new Error('DataCite tidak merespons.');const j=await r.json();return (j.data||[]).map(d=>{const a=d.attributes||{};const title=norm(a.titles?.[0]?.title||'');return{kind:'DataCite',title,url:a.url||(`https://doi.org/${d.id}`),doi:d.id||'',authors:(a.creators||[]).slice(0,3).map(x=>x.name).filter(Boolean).join(', '),year:a.publicationYear||'',container:a.publisher||'',score:overlapScore(title,query)};}).filter(x=>x.title).sort((a,b)=>b.score-a.score).slice(0,5);}
async function searchGdelt(query){const u=`https://api.gdeltproject.org/api/v2/doc/doc?query=${encodeURIComponent(query)}&mode=ArtList&maxrecords=12&format=json&sort=HybridRel`;const r=await fetch(u);if(!r.ok)throw new Error('GDELT tidak merespons.');const j=await r.json();const arr=j.articles||j.items||[];return arr.map(x=>({title:norm(x.title||''),url:x.url||'',domain:x.domain||(()=>{try{return new URL(x.url).hostname}catch{return''}})(),date:x.seendate||x.date||'',language:x.language||'',score:overlapScore(x.title||'',query)})).filter(x=>x.title&&x.url).sort((a,b)=>b.score-a.score).slice(0,8);}
async function webResearch(query,opts){const result={news:[],scholar:[],errors:[]};const jobs=[];if(opts.news)jobs.push(searchGdelt(query).then(x=>result.news=x).catch(e=>result.errors.push(e.message)));if(opts.scholar)jobs.push(searchCrossref(query).then(x=>result.scholar.push(...x)).catch(e=>result.errors.push(e.message)));if(opts.data)jobs.push(searchDataCite(query).then(x=>result.scholar.push(...x)).catch(e=>result.errors.push(e.message)));await Promise.all(jobs);const seen=new Set();result.scholar=result.scholar.filter(x=>{const k=(x.doi||x.title).toLowerCase();if(seen.has(k))return false;seen.add(k);return true;}).sort((a,b)=>b.score-a.score).slice(0,10);return result;}

function sourceRow(l,v){return v?`<div class="source-item"><span>${esc(l)}</span><strong>${esc(v)}</strong></div>`:'';}
function renderSource(a){$('sourceInfo').innerHTML=sourceRow('Judul',a.title||'(tidak terdeteksi)')+sourceRow('Domain',a.domain||'-')+sourceRow('Tanggal',a.published||'-')+sourceRow('Panjang teks',`${a.text.length.toLocaleString('id-ID')} karakter`)+sourceRow('Kalimat',splitSentences(a.text).length)+sourceRow('Paragraf',a.paragraphs?.length||0);$('sourceMethod').textContent=a.method||'Input';$('sourceCard').classList.remove('hidden');}
function renderQuick(q,focus){$('evidenceScore').textContent=`Kekuatan bukti tekstual ${q.strength}/100`;$('quickGrid').innerHTML=q.items.map(([l,v])=>`<div class="quick-item"><span>${esc(l)}</span><p>${esc(v)}</p></div>`).join('');if(norm(focus)){$('focusBox').classList.remove('hidden');$('focusBox').innerHTML=`<h3>Fokus permintaan peneliti</h3><p>${esc(focus)}</p><div class="evidence-title">Bagian teks yang paling terkait</div><ul>${q.focusEvidence.length?q.focusEvidence.map(x=>`<li>${esc(short(x,300))}</li>`).join(''):'<li>Tidak ditemukan kecocokan eksplisit yang cukup kuat. Fokus tetap dipakai untuk riset web.</li>'}</ul>`;}else $('focusBox').classList.add('hidden');$('quickCard').classList.remove('hidden');}
function renderAnalysis(model,data){$('modelName').textContent=MODELS[model];$('summary').innerHTML=`<strong>Frame dominan</strong><p>${esc(data.summary)}</p>`;$('sections').innerHTML=data.sections.map(s=>`<section class="analysis-block"><h3>${esc(s.title)}</h3><p>${esc(s.interpretation)}</p><div class="evidence-title">Bukti/indikator dari teks</div><ul>${(s.evidence||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`).join('');$('conclusion').innerHTML=`<strong>Kesimpulan teoritis</strong><p>${esc(data.conclusion)}</p>`;$('resultCard').classList.remove('hidden');}
function renderWeb(web,query){$('webQuery').textContent=query;const domains=new Set(web.news.map(x=>x.domain).filter(Boolean));const strong=web.scholar.filter(x=>x.score>=30).length;$('webSummary').innerHTML=`<div class="metric"><b>${web.news.length}</b><span>berita pembanding ditemukan</span></div><div class="metric"><b>${domains.size}</b><span>domain berita berbeda</span></div><div class="metric"><b>${web.scholar.length}</b><span>rekaman ilmiah/DOI ditemukan</span></div>`;$('newsResults').innerHTML=web.news.length?web.news.map(x=>`<article class="result-entry"><a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${esc(x.title)}</a><div class="result-meta">${esc(x.domain)}${x.date?' · '+esc(x.date):''}${x.language?' · '+esc(x.language):''}</div><div class="tagline"><span class="tag">overlap ${x.score}%</span></div></article>`).join(''):'<div class="empty">Belum ada berita pembanding yang dapat diambil otomatis. Gunakan tautan pencarian lanjutan di bawah.</div>';$('scholarResults').innerHTML=web.scholar.length?web.scholar.map(x=>`<article class="result-entry"><a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${esc(x.title)}</a><div class="result-meta">${esc([x.authors,x.year,x.container].filter(Boolean).join(' · '))}</div><div class="tagline"><span class="tag">${esc(x.kind)}</span>${x.doi?`<span class="tag">DOI ${esc(x.doi)}</span>`:''}<span class="tag">relevansi istilah ${x.score}%</span></div></article>`).join(''):'<div class="empty">Belum ada metadata ilmiah yang dapat diambil otomatis. Coba fokus pencarian yang lebih spesifik.</div>';$('searchLinks').innerHTML=`<a target="_blank" rel="noopener noreferrer" href="https://scholar.google.com/scholar?q=${encodeURIComponent(query)}">Google Scholar</a><a target="_blank" rel="noopener noreferrer" href="https://news.google.com/search?q=${encodeURIComponent(query)}">Google News</a><a target="_blank" rel="noopener noreferrer" href="https://search.crossref.org/?q=${encodeURIComponent(query)}">Crossref Search</a><a target="_blank" rel="noopener noreferrer" href="https://commons.datacite.org/?query=${encodeURIComponent(query)}">DataCite Commons</a>`;$('webCard').classList.remove('hidden');return{domains:domains.size,strong};}
function renderLimitations(article,quick,webMeta,web){const a=common(article),items=[];items.push({kind:'good',text:'Semua kutipan bukti framing pada laporan berasal dari teks sumber yang dimasukkan/dibaca aplikasi; aplikasi tidak membuat kutipan berita baru.'});if(quick.strength<60)items.push({kind:'warn',text:'Bukti tekstual relatif terbatas. Kesimpulan framing sebaiknya diperlakukan sebagai hipotesis coding awal dan diverifikasi dengan pembacaan manual.'});else items.push({kind:'good',text:'Bukti tekstual cukup untuk coding awal, tetapi penetapan makna laten/ideologi tetap membutuhkan interpretasi peneliti.'});if(!a.causes.length)items.push({kind:'warn',text:'Atribusi sebab tidak muncul secara eksplisit; hindari menyatakan aktor tertentu sebagai penyebab tanpa bukti tambahan.'});if(web.errors?.length)items.push({kind:'warn',text:`Sebagian layanan web gagal diakses: ${web.errors.join(' | ')}. Hasil riset web karena itu belum lengkap.`});if(webMeta.domains<2&&web.news.length)items.push({kind:'warn',text:'Keragaman sumber berita pembanding masih rendah; tambahkan sumber dari domain berbeda sebelum menarik kesimpulan perbandingan media.'});if(web.scholar.length)items.push({kind:'good',text:'Literatur ilmiah yang ditampilkan berasal dari metadata Crossref/DataCite. Judul/DOI adalah hasil retrieval; aplikasi tidak mengklaim temuan artikel sebelum teks penuh dibaca.'});items.push({kind:'',text:'Skor “kekuatan bukti tekstual” adalah indikator kelengkapan bukti yang terdeteksi, bukan probabilitas kebenaran, bukan reliabilitas statistik, dan bukan skor validitas penelitian.'});$('limitations').innerHTML=items.map(x=>`<div class="limitation ${x.kind}">${esc(x.text)}</div>`).join('');$('methodCard').classList.remove('hidden');}
function buildPlain(result){const r=result;let s=`FRAMINGLAB WEB RESEARCH EDITION\nModel: ${MODELS[r.model]}\nJudul: ${r.article.title||'-'}\nURL: ${r.article.url||'-'}\nFokus: ${r.focus||'-'}\nQuery web: ${r.query}\n\nINTERPRETASI MUDAH\n`;for(const [l,v] of r.quick.items)s+=`\n${l}: ${v}\n`;s+=`\nFRAME DOMINAN\n${r.analysis.summary}\n`;for(const sec of r.analysis.sections)s+=`\n${sec.title}\n${sec.interpretation}\n- ${(sec.evidence||[]).join('\n- ')}\n`;s+=`\nKESIMPULAN\n${r.analysis.conclusion}\n\nBERITA PEMBANDING\n`;for(const x of r.web.news)s+=`- ${x.title} | ${x.domain} | ${x.url}\n`;s+=`\nLITERATUR / DOI\n`;for(const x of r.web.scholar)s+=`- ${x.title} | ${x.authors||''} | ${x.year||''} | ${x.doi||x.url}\n`;return s;}
function download(name,content,type){const b=new Blob([content],{type});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function reportHtml(r){return `<!doctype html><html lang="id"><meta charset="utf-8"><title>Laporan FramingLab</title><style>body{font:14px Arial;max-width:900px;margin:40px auto;line-height:1.55}h1,h2,h3{color:#4c1d95}blockquote{background:#faf5ff;border-left:4px solid #7c3aed;padding:10px 14px}li{margin:6px 0}a{color:#5b21b6}</style><h1>FramingLab — Laporan Analisis</h1><p><b>Model:</b> ${esc(MODELS[r.model])}<br><b>Judul:</b> ${esc(r.article.title||'-')}<br><b>URL:</b> ${esc(r.article.url||'-')}<br><b>Fokus:</b> ${esc(r.focus||'-')}<br><b>Query web:</b> ${esc(r.query)}</p><h2>Interpretasi mudah</h2>${r.quick.items.map(([l,v])=>`<h3>${esc(l)}</h3><p>${esc(v)}</p>`).join('')}<h2>Analisis framing</h2><blockquote>${esc(r.analysis.summary)}</blockquote>${r.analysis.sections.map(s=>`<h3>${esc(s.title)}</h3><p>${esc(s.interpretation)}</p><ul>${s.evidence.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`).join('')}<h2>Kesimpulan</h2><p>${esc(r.analysis.conclusion)}</p><h2>Berita pembanding</h2><ul>${r.web.news.map(x=>`<li><a href="${esc(x.url)}">${esc(x.title)}</a> — ${esc(x.domain)}</li>`).join('')||'<li>Tidak tersedia</li>'}</ul><h2>Literatur ilmiah/DOI</h2><ul>${r.web.scholar.map(x=>`<li><a href="${esc(x.url)}">${esc(x.title)}</a> — ${esc([x.authors,x.year,x.container].filter(Boolean).join(', '))}${x.doi?' — DOI '+esc(x.doi):''}</li>`).join('')||'<li>Tidak tersedia</li>'}</ul><p><small>Catatan: sumber web adalah konteks pembanding. Verifikasi sumber asli dan teks penuh sebelum membuat klaim akademik.</small></p></html>`;}

async function analyze(){clearStatus();['sourceCard','quickCard','resultCard','webCard','methodCard'].forEach(id=>$(id).classList.add('hidden'));const model=$('model').value,url=$('url').value.trim(),manual=$('text').value.trim(),manualTitle=$('title').value.trim(),focus=$('focus').value.trim();if(!url&&!manual){setStatus('Tempel URL atau isi berita terlebih dahulu.','error');return;}const btn=$('analyzeBtn');btn.disabled=true;btn.textContent='SEDANG MENGANALISIS & MENCARI SUMBER...';setStatus('Menyiapkan teks utama, melakukan coding framing, lalu mencari sumber pembanding dan literatur ilmiah...','info');try{let article,warning='';if(manual){article=manualArticle(manual,manualTitle,url);}else{try{article=await readUrlWithJina(url);if(manualTitle)article.title=manualTitle;}catch(e){warning=e.message;$('manualBox').open=true;throw new Error(`${e.message} Tempel isi berita pada kolom manual lalu jalankan kembali.`);}}if(article.text.length<180)throw new Error('Teks terlalu pendek untuk dianalisis secara bertanggung jawab.');const analysis=analyzeModel(model,article);const quick=buildQuick(article,analysis,focus);const query=buildQuery(article,focus);renderSource(article);renderQuick(quick,focus);renderAnalysis(model,analysis);setStatus('Analisis teks selesai. Menelusuri web relevan...','info');const web=await webResearch(query,{news:$('searchNews').checked,scholar:$('searchScholar').checked,data:$('searchData').checked});const webMeta=renderWeb(web,query);renderLimitations(article,quick,webMeta,web);lastResult={model,article,focus,analysis,quick,query,web,createdAt:new Date().toISOString()};setStatus(web.errors.length?`Selesai dengan catatan: ${web.errors.join(' | ')}`:'Selesai. Interpretasi framing dan riset web pendukung tersedia.',web.errors.length?'warn':'ok');$('quickCard').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){setStatus(e.message||'Analisis gagal.','error');}finally{btn.disabled=false;btn.textContent='ANALISIS + RISET WEB';}}
$('analyzeBtn').addEventListener('click',analyze);$('url').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();analyze();}});$('downloadTxtBtn').addEventListener('click',()=>lastResult&&download('hasil_framinglab.txt',buildPlain(lastResult),'text/plain;charset=utf-8'));$('downloadJsonBtn').addEventListener('click',()=>lastResult&&download('hasil_framinglab.json',JSON.stringify(lastResult,null,2),'application/json;charset=utf-8'));$('downloadHtmlBtn').addEventListener('click',()=>lastResult&&download('laporan_framinglab.html',reportHtml(lastResult),'text/html;charset=utf-8'));
