'use strict';
const $=id=>document.getElementById(id);
const MODELS={entman:'Robert N. Entman',pan_kosicki:'Zhongdang Pan & Gerald M. Kosicki',gamson_modigliani:'William A. Gamson & Andre Modigliani',edelman:'Murray Edelman'};
const THEORY_QUERIES={
 entman:'Entman framing fractured paradigm media communication framing',
 pan_kosicki:'Pan Kosicki framing analysis news discourse syntactical script thematic rhetorical',
 gamson_modigliani:'Gamson Modigliani media discourse interpretive packages framing devices reasoning devices',
 edelman:'Murray Edelman framing categorization political spectacle media'
};
const STOPWORDS=new Set(`yang dan di ke dari untuk dengan pada adalah itu ini dalam sebagai oleh atau juga karena agar akan telah sudah belum tidak bisa dapat suatu sebuah para mereka kami kita ia dia hingga sampai antara terhadap terkait tentang namun tetapi serta menjadi pun lebih sangat saat ketika jika maka ada kepada tersebut setelah sebelum luar masih hanya kembali bagi melalui sejak tahun bulan hari secara seorang beberapa salah satu dua tiga empat lima enam tujuh delapan sembilan sepuluh kata menurut ujar mengatakan menyebut menjelaskan menyatakan pihak hal atas bawah lalu kemudian yakni yaitu bahwa media berita dilakukan melakukan merupakan soal kasus orang warga pemerintah daerah kota kabupaten indonesia hari page website security verification captcha authorized access malicious bots browser javascript enable cookies cloudflare`.split(/\s+/));
const CAUSE_MARKERS=['karena','akibat','sebab','disebabkan','dipicu','berawal','lantaran','sehingga','menyebabkan','berdampak','berujung','alasan','dilatarbelakangi'];
const MORAL_MARKERS=['harus','seharusnya','semestinya','wajib','penting','adil','tidak adil','melanggar','pelanggaran','benar','salah','layak','tidak layak','wajar','bertanggung jawab','hak','kewajiban','moral','etika','patut','tidak patut'];
const TREATMENT_MARKERS=['solusi','menyelesaikan','penyelesaian','meminta','mendorong','mengusulkan','menunda','menghentikan','melanjutkan','menindak','menetapkan','memutuskan','perlu','upaya','langkah','rekomendasi','jalan keluar','mediasi','negosiasi','proses hukum','pengadilan','dialog','evaluasi','meninjau','mencegah'];
const EVALUATIVE_WORDS=['keras','tegas','genting','serius','krusial','kontroversial','dramatis','ancaman','korban','ilegal','sengketa','konflik','gugatan','krisis','desak','menolak','mendukung','mengecam','memprotes','mempertahankan','merugikan','meresahkan','bermasalah','penting'];
const SECURITY_PATTERNS=[/captcha/i,/security verification/i,/verify you are not a bot/i,/verifies you are not a bot/i,/checking your browser/i,/access denied/i,/enable javascript/i,/enable cookies/i,/cloudflare/i,/malicious bots/i,/authorized to access this page/i,/performing security verification/i,/human verification/i,/robot check/i,/blocked request/i];
let lastResult=null;

function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function norm(s){return String(s??'').replace(/\s+/g,' ').trim();}
function short(s,n=360){s=norm(s);return !s?'Tidak teridentifikasi dari data yang tersedia.':(s.length<=n?s:s.slice(0,n-1).trim()+'…');}
function setStatus(msg,kind='info'){const e=$('status');e.className=`status ${kind}`;e.textContent=msg;}
function clearStatus(){$('status').className='status hidden';$('status').textContent='';}
function splitSentences(text){return norm(text).split(/(?<=[.!?])\s+/).map(norm).filter(x=>x.length>=30);}
function tokens(text){return (String(text).toLowerCase().match(/[a-zà-öø-ÿ0-9-]{3,}/gi)||[]).map(x=>x.toLowerCase()).filter(x=>!STOPWORDS.has(x)&&!/^[0-9]+$/.test(x));}
function topTerms(text,n=15){const m=new Map();for(const t of tokens(text))m.set(t,(m.get(t)||0)+1);return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,n);}
function sentencesWith(sents,markers,limit=4){return sents.map((s,i)=>({s,i,h:markers.reduce((n,m)=>n+(s.toLowerCase().includes(m)?1:0),0)})).filter(x=>x.h).sort((a,b)=>b.h-a.h||a.i-b.i).slice(0,limit).map(x=>x.s);}
function evidence(items,empty='Tidak ditemukan secara eksplisit dalam teks.'){return items?.length?items.map(x=>short(x)):[empty];}
function stripHtml(s){const d=document.createElement('div');d.innerHTML=String(s||'');return norm(d.textContent||d.innerText||'');}
function domainOf(url){try{return new URL(url).hostname.replace(/^www\./,'')}catch{return''}}
function cleanBoilerplate(text){return String(text||'').split(/\n+/).map(x=>x.trim()).filter(x=>x&&x.length>2&&!/^(share|advertisement|iklan|related|recommended|baca juga|follow us|subscribe|login|sign in)\b/i.test(x)).join('\n');}
function qualityCheck(article){const text=norm(article.text);const hits=SECURITY_PATTERNS.filter(r=>r.test(text)).map(r=>r.source.replace(/\\b/g,''));const sents=splitSentences(text);const words=tokens(text);const unique=new Set(words);const titleBad=SECURITY_PATTERNS.some(r=>r.test(article.title||''));const ratio=words.length?unique.size/words.length:0;const issues=[];
 if(hits.length||titleBad)issues.push('Teks terdeteksi sebagai halaman keamanan/CAPTCHA atau halaman penolakan akses, bukan artikel berita.');
 if(text.length<500)issues.push('Teks sumber sangat pendek untuk analisis framing yang stabil.');
 if(sents.length<5)issues.push('Jumlah kalimat substantif terlalu sedikit.');
 if(words.length>30&&ratio<0.18)issues.push('Teks tampak sangat repetitif dan berpotensi berupa boilerplate/non-artikel.');
 const fatal=!!(hits.length||titleBad||text.length<180||sents.length<2);
 return{fatal,issues,hits,sentences:sents.length,words:words.length,uniqueRatio:ratio};}
function common(article){const sents=splitSentences(article.text);return{sentences:sents,terms:topTerms(`${article.title||''} ${article.text}`,15),causes:sentencesWith(sents,CAUSE_MARKERS),morals:sentencesWith(sents,MORAL_MARKERS),treatments:sentencesWith(sents,TREATMENT_MARKERS),evaluative:sentencesWith(sents,EVALUATIVE_WORDS)};}
function extractActors(text){const matches=text.match(/\b[A-Z][A-Za-zÀ-ÖØ-öø-ÿ.'’-]{2,}(?:\s+[A-Z][A-Za-zÀ-ÖØ-öø-ÿ.'’-]{2,}){0,3}\b/g)||[];const bad=new Set(['Indonesia','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu','Title','Markdown Content','URL Source']);const m=new Map();for(const x of matches){const n=norm(x);if(bad.has(n))continue;m.set(n,(m.get(n)||0)+1);}return[...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6).map(x=>x[0]);}
function topicPhrase(a,n=5){return a.terms.slice(0,n).map(x=>x[0]).join(', ')||'isu utama dalam teks';}
function dominantFrame(a,actors=[]){const t=topicPhrase(a,5);const ac=actors.slice(0,3).join(', ');return`Teks memusatkan perhatian pembaca pada ${t}${ac?`, dengan ${ac} sebagai aktor/entitas yang paling menonjol`:''}. Penonjolan tersebut tampak melalui posisi judul/lead, pengulangan istilah, dan bagian teks yang memperoleh ruang penjelasan lebih besar.`;}
function gapSentence(a){const g=[];if(!a.causes.length)g.push('hubungan sebab-akibat tidak dinyatakan tegas');if(!a.morals.length)g.push('evaluasi normatif tidak dominan');if(!a.treatments.length)g.push('solusi atau arah tindakan belum ditonjolkan');return g.length?`Namun, ${g.join(', ')}.`:'Teks juga memuat atribusi sebab, evaluasi, dan arah tindakan yang relatif dapat ditelusuri secara eksplisit.';}
function analyzeEntman(article){const a=common(article),actors=extractActors(article.text),def=a.sentences.slice(0,4),topic=topicPhrase(a);return{summary:dominantFrame(a,actors),narrative:`Dalam kerangka Robert N. Entman, framing dapat dibaca dari fungsi pendefinisian masalah, atribusi penyebab, penilaian moral, dan rekomendasi penanganan. Pada teks ini, fungsi paling kuat adalah pendefinisian masalah: judul, lead, dan pengulangan istilah mengarahkan pembaca melihat ${topic} sebagai pusat persoalan. ${gapSentence(a)} Karena itu, frame sebaiknya dirumuskan dari apa yang benar-benar ditonjolkan teks, bukan dari unsur yang tidak hadir.`,sections:[{title:'Define Problems — bagaimana masalah dibentuk',interpretation:`Masalah dikonstruksi terutama melalui judul dan bagian awal. Teks menempatkan ${topic} sebagai konteks yang perlu dianggap penting oleh pembaca. Secara analitis, bagian ini menunjukkan apa yang dipilih media untuk masuk ke pusat perhatian dan apa yang ditempatkan sebagai latar.`,evidence:evidence(def)},{title:'Diagnose Causes — siapa/apa yang diberi tanggung jawab kausal',interpretation:a.causes.length?`Terdapat atribusi sebab yang dapat dilacak secara eksplisit. Kalimat-kalimat berikut menghubungkan peristiwa dengan penyebab, kondisi pemicu, atau konsekuensi. Interpretasi kausal harus tetap mengikuti relasi yang tertulis.`:'Atribusi kausal tidak dinyatakan secara eksplisit. Dalam pembacaan Entman, ketiadaan ini penting: teks lebih kuat mendeskripsikan masalah daripada menetapkan penyebab. Karena itu aplikasi tidak mengisi kekosongan dengan asumsi tentang siapa yang bersalah.',evidence:evidence(a.causes)},{title:'Make Moral Judgment — legitimasi, kepatutan, atau evaluasi',interpretation:a.morals.length?'Bahasa normatif memberi petunjuk mengenai tindakan atau aktor yang dilegitimasi, dipersoalkan, atau dinilai. Penilaian moral dibaca hanya ketika ada kata/kalimat evaluatif yang cukup jelas.':'Tidak tampak penilaian moral yang kuat. Ini berarti frame dapat bekerja melalui seleksi fakta dan penonjolan tema tanpa harus memakai bahasa yang secara terbuka menilai benar/salah.',evidence:evidence(a.morals)},{title:'Treatment Recommendation — arah solusi atau tindakan',interpretation:a.treatments.length?'Teks menawarkan atau menonjolkan langkah tindak lanjut. Bagian ini menunjukkan jalan keluar yang dibuat lebih masuk akal atau lebih layak di mata pembaca.':'Arah penyelesaian tidak dinyatakan secara eksplisit. Karena itu tidak tepat menyimpulkan bahwa media merekomendasikan solusi tertentu hanya dari deskripsi masalah.',evidence:evidence(a.treatments)}],conclusion:`Secara keseluruhan, frame teks berpusat pada ${topic}. Penafsiran paling kuat berada pada cara masalah didefinisikan dan istilah tertentu diberi saliens. Unsur kausal, moral, atau solusi hanya boleh disimpulkan sejauh muncul dalam bukti tekstual. Dengan demikian, hasil ini merupakan pembacaan framing berbasis teks yang dapat diuji kembali melalui perbandingan berita dan literatur.`};}
function analyzePan(article){const a=common(article),s=a.sentences,actors=extractActors(article.text),quotes=[...article.text.matchAll(/[“"]([^”"]{20,260})[”"]/g)].map(m=>m[1]),topic=topicPhrase(a),low=article.text.toLowerCase();const wh={What:!!(article.title||s.length),Who:actors.length>0,When:/\b(senin|selasa|rabu|kamis|jumat|sabtu|minggu|20\d{2})\b/i.test(low),Where:/\b(di|dari|menuju)\s+[A-Z][A-Za-z.-]+/.test(article.text),Why:!!a.causes.length,How:!!a.treatments.length||/\b(dengan cara|melalui|mekanisme|proses)\b/i.test(low)};return{summary:dominantFrame(a,actors),narrative:`Dalam model Pan & Kosicki, framing dibaca sebagai strategi organisasi wacana. Pada teks ini, struktur sintaksis dan tematik paling terlihat melalui judul/lead serta pengulangan tema ${topic}. Kelengkapan skrip dapat dilihat dari unsur 5W+1H, sementara kutipan dan istilah evaluatif memperlihatkan siapa yang memperoleh suara dan bagaimana penekanan retoris dibangun.`,sections:[{title:'Sintaksis — organisasi headline, lead, latar, dan sumber',interpretation:`Headline dan lead membentuk pintu masuk pembaca ke isu. Aktor yang sering muncul (${actors.slice(0,4).join(', ')||'belum cukup teridentifikasi'}) mendapat posisi diskursif lebih kuat. Kutipan langsung terdeteksi sebanyak ${quotes.length}.`,evidence:evidence([article.title,...s.slice(0,2),...quotes.slice(0,2)].filter(Boolean))},{title:'Skrip — kelengkapan cerita 5W+1H',interpretation:`Struktur cerita terdeteksi sebagai: ${Object.entries(wh).map(([k,v])=>`${k} ${v?'terlihat':'belum jelas'}`).join('; ')}. Kekosongan pada Why/How penting karena dapat menunjukkan berita lebih deskriptif daripada eksplanatif.`,evidence:evidence([...a.causes.slice(0,2),...a.treatments.slice(0,2)],'Unsur sebab/cara belum cukup eksplisit dalam teks.')},{title:'Tematik — hubungan antarkalimat dan tema utama',interpretation:`Tema dominan adalah ${topic}. Pengulangan dan koherensi antarkalimat menunjukkan bagaimana detail disusun agar pembaca melihat isu dalam pola yang relatif konsisten.`,evidence:evidence(s.slice(0,4))},{title:'Retoris — pilihan kata, label, kutipan, dan penekanan',interpretation:a.evaluative.length?'Pilihan kata evaluatif memberi intensitas pada isu dan dapat menguatkan posisi tertentu tanpa harus menyatakan sikap editorial secara langsung.':'Penekanan retoris eksplisit terbatas. Frame lebih banyak bekerja melalui struktur dan pemilihan fakta daripada melalui kata-kata evaluatif yang kuat.',evidence:evidence([...a.evaluative,...quotes.slice(0,2)].slice(0,5))}],conclusion:`Framing menurut Pan & Kosicki pada teks ini terutama dibentuk melalui struktur headline/lead, pilihan sumber, dan kesinambungan tema ${topic}. Interpretasi retoris dan ideologis perlu diperkuat dengan membandingkan berita lain pada peristiwa yang sama.`};}
function analyzeGamson(article){const a=common(article),actors=extractActors(article.text),quotes=[...article.text.matchAll(/[“"]([^”"]{8,180})[”"]/g)].map(m=>m[1]),met=sentencesWith(a.sentences,['ibarat','bak ','laksana','umpama','seperti ','bagaikan'],3),ex=(article.paragraphs||[]).filter(p=>/\b(misalnya|contohnya|sebagai contoh|kasus)\b/i.test(p)).slice(0,3),core=topicPhrase(a);return{summary:`Paket interpretatif teks paling kuat berpusat pada ${core}${actors.length?`, dengan ${actors.slice(0,3).join(', ')} sebagai figur/entitas yang menonjol`:''}.`,narrative:`Model Gamson & Modigliani memandang frame sebagai paket interpretatif yang memadukan perangkat framing dan perangkat penalaran. Pada teks ini, gagasan sentral muncul dari pengulangan ${core}. Metafora, contoh, kutipan, dan label menjadi perangkat pembentuk makna, sedangkan relasi sebab serta klaim normatif menjadi alasan yang membuat frame terasa masuk akal.`,sections:[{title:'Core Frame — gagasan sentral',interpretation:`Gagasan sentral yang paling konsisten adalah ${core}. Ia menjadi benang merah yang menghubungkan informasi yang tersebar dalam teks.`,evidence:evidence(a.sentences.slice(0,4))},{title:'Framing Devices — simbol, label, metafora, contoh, dan kutipan',interpretation:'Perangkat framing menunjukkan cara teks membuat suatu isu mudah dikenali dan diingat. Bukti berikut merupakan perangkat eksplisit yang paling dekat dengan kategori tersebut.',evidence:evidence([...met,...ex,...quotes.slice(0,3),...a.evaluative.slice(0,2)].slice(0,7),'Perangkat simbolik/metaforis eksplisit terbatas pada input ini.')},{title:'Reasoning Devices — Roots',interpretation:a.causes.length?'Hubungan sebab-akibat berfungsi sebagai roots: ia memberi penjelasan mengapa situasi terjadi dan mengapa pembaca sebaiknya memahami isu dalam arah tertentu.':'Roots tidak dinyatakan tegas. Artinya paket framing lebih bertumpu pada penonjolan isu daripada penjelasan kausal.',evidence:evidence(a.causes)},{title:'Reasoning Devices — Appeal to Principle',interpretation:a.morals.length?'Prinsip normatif memberi dasar legitimasi terhadap penilaian yang dibangun teks.':'Tidak ada appeal to principle yang cukup eksplisit; peneliti sebaiknya tidak memaksakan nilai moral yang tidak tertulis.',evidence:evidence(a.morals)}],conclusion:`Interpretative package yang terbaca berpusat pada ${core}. Kekuatan paket terutama ditentukan oleh konsistensi gagasan sentral dan perangkat penonjol; makna simbolik laten harus diuji dengan konteks budaya, sumber pembanding, dan literatur.`};}
function guessSection(article){const hay=`${article.url||''} ${article.text.slice(0,5000)}`.toLowerCase(),mapping={hukum:['hukum','gugatan','pengadilan','putusan','pidana','perdata'],politik:['politik','pemilu','partai','dpr','pilkada','pemerintah'],ekonomi:['ekonomi','bisnis','pasar','keuangan','investasi'],kriminal:['kriminal','polisi','tersangka','penangkapan'],pendidikan:['pendidikan','sekolah','kampus','mahasiswa','pesantren'],sosial:['sosial','warga','masyarakat','komunitas']};let best=['tidak teridentifikasi',0];for(const[k,arr]of Object.entries(mapping)){const score=arr.reduce((n,w)=>n+(hay.split(w).length-1),0);if(score>best[1])best=[k,score];}return best[0];}
function analyzeEdelman(article){const a=common(article),actors=extractActors(article.text),cat=guessSection(article),topic=topicPhrase(a);return{summary:`Teks mengkategorisasikan realitas terutama sebagai isu ${cat}, dengan label dominan ${topic}.`,narrative:`Dalam perspektif Murray Edelman, kategori dan label bukan sekadar deskripsi, tetapi dapat menyederhanakan realitas kompleks dan mengarahkan perhatian. Pada teks ini, rubrikasi ${cat} dan pengulangan ${topic} membuat aspek tertentu lebih mudah dikenali sebagai “masalah utama”. Aplikasi tidak menetapkan ideologi media; ia hanya menunjukkan jejak kategorisasi yang dapat diperiksa peneliti.`,sections:[{title:'Kategorisasi — nama masalah dan batas realitas',interpretation:`Judul, lead, dan istilah dominan menempatkan peristiwa dalam kategori ${cat}. Kategori ini mengorganisasi cara pembaca mengenali siapa/apa yang relevan dan bagian mana yang dianggap sekunder.`,evidence:evidence([article.title,...a.sentences.slice(0,3)].filter(Boolean))},{title:'Rubrikasi — penempatan isu dalam ranah tertentu',interpretation:`Rubrikasi diperkirakan berada pada ranah ${cat}. Penempatan semacam ini dapat mempengaruhi harapan pembaca terhadap jenis penjelasan dan aktor yang dianggap penting.`,evidence:evidence([`Domain sumber: ${article.domain||'-'}`,`Aktor menonjol: ${actors.join(', ')||'belum cukup teridentifikasi'}`])},{title:'Pelabelan dan implikasi',interpretation:a.evaluative.length?'Label dan kata evaluatif berikut berpotensi memperkuat citra aktor/peristiwa. Implikasi politik atau ideologis tetap harus diuji melalui perbandingan sumber.':'Bahasa evaluatif kuat tidak terdeteksi; efek kategorisasi lebih mungkin berasal dari pemilihan isu dan label topikal.',evidence:evidence(a.evaluative.slice(0,5),'Tidak ditemukan label evaluatif yang cukup kuat.')}],conclusion:`Dalam model Edelman, frame terutama tampak melalui kategorisasi ${cat} dan pengulangan label ${topic}. Klaim mengenai ideologi atau kepentingan media tidak boleh dibuat hanya dari satu teks dan membutuhkan pembanding eksternal.`};}
function analyzeModel(model,article){return model==='pan_kosicki'?analyzePan(article):model==='gamson_modigliani'?analyzeGamson(article):model==='edelman'?analyzeEdelman(article):analyzeEntman(article);}
function focusEvidence(article,focus){const f=tokens(focus).filter(x=>x.length>3);if(!f.length)return[];return splitSentences(article.text).map(s=>({s,h:f.reduce((n,w)=>n+(s.toLowerCase().includes(w)?1:0),0)})).filter(x=>x.h).sort((a,b)=>b.h-a.h).slice(0,5).map(x=>x.s);}
function evidenceStrength(article,a,q){let s=20;s+=Math.min(20,article.text.length/500);s+=Math.min(15,a.sentences.length/3);s+=Math.min(10,a.causes.length*3);s+=Math.min(10,a.morals.length*2);s+=Math.min(10,a.treatments.length*2);s+=Math.min(10,([...(article.text.matchAll(/[“"]/g))].length));if(q?.issues?.length)s-=q.issues.length*8;return Math.max(0,Math.min(100,Math.round(s)));}
function buildQuick(article,analysis,focus,q){const a=common(article),actors=extractActors(article.text),strength=evidenceStrength(article,a,q),terms=a.terms.slice(0,6).map(x=>x[0]),gaps=[];if(!a.causes.length)gaps.push('penyebab tidak eksplisit');if(!a.morals.length)gaps.push('evaluasi normatif terbatas');if(!a.treatments.length)gaps.push('arah solusi belum eksplisit');if(!/[“"]/.test(article.text))gaps.push('kutipan langsung tidak terdeteksi');return{strength,items:[['Pokok persoalan',analysis.summary],['Aktor/entitas utama',actors.length?actors.join(', '):'Belum dapat diidentifikasi dengan cukup kuat.'],['Tema/istilah dominan',terms.join(', ')||'Belum cukup data.'],['Cara teks menjelaskan sebab',a.causes[0]?short(a.causes[0],280):'Teks tidak menetapkan penyebab secara eksplisit; hal ini harus dibaca sebagai ketiadaan bukti, bukan izin untuk menebak sebab.'],['Arah evaluasi',a.morals[0]?short(a.morals[0],280):'Penilaian normatif tidak menonjol; frame mungkin bekerja melalui seleksi dan penempatan fakta.'],['Batas pembacaan',gaps.length?`Interpretasi perlu hati-hati karena ${gaps.join(', ')}.`:'Bukti tekstual relatif lengkap untuk coding awal, tetapi tetap perlu triangulasi konteks.']],focusEvidence:focusEvidence(article,focus)};}

async function readUrlWithJina(url){const u=norm(url);if(!/^https?:\/\//i.test(u))throw new Error('Alamat URL harus diawali http:// atau https://');const endpoint='https://r.jina.ai/'+u,r=await fetch(endpoint,{method:'GET'});if(!r.ok)throw new Error(`Reader gagal membaca URL (HTTP ${r.status}).`);const raw=await r.text(),title=(raw.match(/^Title:\s*(.+)$/mi)||[])[1]||'',published=(raw.match(/^Published Time:\s*(.+)$/mi)||[])[1]||'';let content=raw.replace(/^Title:.*$/mi,'').replace(/^URL Source:.*$/mi,'').replace(/^Published Time:.*$/mi,'').replace(/^Markdown Content:\s*/mi,'');content=content.replace(/!\[[^\]]*\]\([^)]*\)/g,' ').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/^#{1,6}\s+/gm,'').replace(/[*_`>#]/g,' ');content=cleanBoilerplate(content).slice(0,80000);const article={url:u,domain:domainOf(u),title:norm(title),published:norm(published),author:'',section:'',text:content,paragraphs:content.split(/\n+/).map(norm).filter(x=>x.length>=30),method:'Jina Reader'};const q=qualityCheck(article);if(q.fatal)throw new Error(`Teks dari URL bukan artikel yang layak dianalisis. ${q.issues.join(' ')} Tempel teks artikel secara manual agar hasil tidak salah.`);return article;}
function manualArticle(text,title,url=''){const t=cleanBoilerplate(String(text||'').trim().slice(0,80000));return{url,domain:url?domainOf(url):'',title:norm(title),published:'',author:'',section:'',text:t,paragraphs:t.split(/\n+/).map(norm).filter(x=>x.length>=30),method:'Teks manual'};}
function buildQuery(article,focus){const ft=tokens(focus).filter(x=>x.length>3).slice(0,7),tt=topTerms(`${article.title} ${article.text}`,8).map(x=>x[0]);return[...new Set([...ft,...tt])].slice(0,8).join(' ')||article.title||'media framing';}
function buildTheoryQuery(model,article){const named=extractActors(article.text).slice(0,2).join(' '),terms=topTerms(article.title+' '+article.text,5).map(x=>x[0]).join(' ');return `${THEORY_QUERIES[model]} ${named} ${terms}`.trim();}
function overlapScore(title,query){const q=new Set(tokens(query)),t=new Set(tokens(title));if(!q.size)return 0;let n=0;for(const x of q)if(t.has(x))n++;return Math.round(100*n/q.size);}
function cleanTitle(x){return Array.isArray(x)?norm(x[0]||''):norm(x||'');}
function yearFromCrossref(w){const p=w['published-print']||w['published-online']||w.published||w.issued;return p?.['date-parts']?.[0]?.[0]||'';}
function authorFromCrossref(w){return(w.author||[]).slice(0,4).map(a=>[a.given,a.family].filter(Boolean).join(' ')).join(', ')+(w.author?.length>4?' et al.':'');}
async function searchCrossref(query,label='Crossref',rows=10){const u=`https://api.crossref.org/works?query.bibliographic=${encodeURIComponent(query)}&rows=${rows}&sort=relevance`;const r=await fetch(u);if(!r.ok)throw new Error('Crossref tidak merespons.');const j=await r.json();return(j.message?.items||[]).map(w=>({kind:label,title:cleanTitle(w.title),url:w.URL||(`https://doi.org/${w.DOI}`),doi:w.DOI||'',authors:authorFromCrossref(w),year:yearFromCrossref(w),container:cleanTitle(w['container-title']),abstract:short(stripHtml(w.abstract||''),900),type:w.type||'',score:overlapScore(cleanTitle(w.title),query)})).filter(x=>x.title).sort((a,b)=>b.score-a.score);}
async function searchDataCite(query){const u=`https://api.datacite.org/dois?query=${encodeURIComponent(query)}&page%5Bsize%5D=8&sort=relevance`,r=await fetch(u);if(!r.ok)throw new Error('DataCite tidak merespons.');const j=await r.json();return(j.data||[]).map(d=>{const a=d.attributes||{},title=norm(a.titles?.[0]?.title||''),desc=Array.isArray(a.descriptions)?a.descriptions.map(x=>x.description).join(' '):'';return{kind:'DataCite',title,url:a.url||(`https://doi.org/${d.id}`),doi:d.id||'',authors:(a.creators||[]).slice(0,4).map(x=>x.name).filter(Boolean).join(', '),year:a.publicationYear||'',container:a.publisher||'',abstract:short(stripHtml(desc),900),type:a.types?.resourceTypeGeneral||'',score:overlapScore(title,query)};}).filter(x=>x.title).sort((a,b)=>b.score-a.score);}
async function searchGdelt(query){const u=`https://api.gdeltproject.org/api/v2/doc/doc?query=${encodeURIComponent(query)}&mode=ArtList&maxrecords=15&format=json&sort=HybridRel`,r=await fetch(u);if(!r.ok)throw new Error('GDELT tidak merespons.');const j=await r.json(),arr=j.articles||j.items||[];return arr.map(x=>({title:norm(x.title||''),url:x.url||'',domain:x.domain||domainOf(x.url),date:x.seendate||x.date||'',language:x.language||'',score:overlapScore(x.title||'',query)})).filter(x=>x.title&&x.url).sort((a,b)=>b.score-a.score).slice(0,10);}
async function searchOpenLibrary(query){const u=`https://openlibrary.org/search.json?q=${encodeURIComponent(query)}&limit=8&fields=key,title,author_name,first_publish_year,publisher,isbn,subject`,r=await fetch(u);if(!r.ok)throw new Error('Open Library tidak merespons.');const j=await r.json();return(j.docs||[]).map(d=>({kind:'Open Library',title:norm(d.title||''),url:d.key?`https://openlibrary.org${d.key}`:'https://openlibrary.org/search?q='+encodeURIComponent(d.title||query),authors:(d.author_name||[]).slice(0,4).join(', '),year:d.first_publish_year||'',container:(d.publisher||[])[0]||'',abstract:'',type:'book',score:overlapScore(d.title||'',query)})).filter(x=>x.title).sort((a,b)=>b.score-a.score).slice(0,6);}
function invertAbstract(inv){if(!inv)return'';const arr=[];for(const[word,positions]of Object.entries(inv))for(const p of positions)arr[p]=word;return norm(arr.filter(Boolean).join(' '));}
async function searchOpenAlex(query,key){if(!key)return[];const u=`https://api.openalex.org/works?search=${encodeURIComponent(query)}&per-page=8&api_key=${encodeURIComponent(key)}`,r=await fetch(u);if(!r.ok)throw new Error(`OpenAlex tidak merespons (HTTP ${r.status}).`);const j=await r.json();return(j.results||[]).map(w=>({kind:'OpenAlex',title:norm(w.display_name||w.title||''),url:w.doi||w.primary_location?.landing_page_url||w.id||'',doi:(w.doi||'').replace(/^https?:\/\/doi.org\//,''),authors:(w.authorships||[]).slice(0,4).map(a=>a.author?.display_name).filter(Boolean).join(', '),year:w.publication_year||'',container:w.primary_location?.source?.display_name||'',abstract:short(invertAbstract(w.abstract_inverted_index),900),type:w.type||'',score:overlapScore(w.display_name||'',query),citedBy:w.cited_by_count||0})).filter(x=>x.title).sort((a,b)=>(b.score-a.score)||(b.citedBy-a.citedBy));}
function parseNotes(text){return String(text||'').split(/\n{2,}|\n[-•]\s*/).map(norm).filter(x=>x.length>=30).slice(0,12).map((x,i)=>({id:`N${i+1}`,text:x}));}
async function webResearch(query,theoryQuery,opts){const result={news:[],scholar:[],books:[],errors:[]},jobs=[];if(opts.news)jobs.push(searchGdelt(query).then(x=>result.news=x).catch(e=>result.errors.push(e.message)));if(opts.scholar){jobs.push(searchCrossref(query,'Crossref — topik',10).then(x=>result.scholar.push(...x)).catch(e=>result.errors.push(e.message)));jobs.push(searchCrossref(query+' Indonesia','Crossref — konteks Indonesia',8).then(x=>result.scholar.push(...x)).catch(e=>result.errors.push(e.message)));jobs.push(searchCrossref(theoryQuery,'Crossref — landasan teori',8).then(x=>result.scholar.push(...x)).catch(e=>result.errors.push(e.message)));}if(opts.data)jobs.push(searchDataCite(query).then(x=>result.scholar.push(...x)).catch(e=>result.errors.push(e.message)));if(opts.books)jobs.push(searchOpenLibrary(theoryQuery).then(x=>result.books=x).catch(e=>result.errors.push(e.message)));if(opts.openAlexKey)jobs.push(searchOpenAlex(theoryQuery,opts.openAlexKey).then(x=>result.scholar.push(...x)).catch(e=>result.errors.push(e.message)));await Promise.all(jobs);const seen=new Set();result.scholar=result.scholar.filter(x=>{const k=(x.doi||x.title).toLowerCase();if(seen.has(k))return false;seen.add(k);return true;}).sort((a,b)=>b.score-a.score).slice(0,opts.maxSources||10);return result;}

function literatureTerms(web,article){const sourceText=web.scholar.slice(0,8).map(x=>`${x.title} ${x.abstract||''}`).join(' ')+' '+web.books.slice(0,4).map(x=>x.title).join(' ');const articleSet=new Set(topTerms(article.text,20).map(x=>x[0]));return topTerms(sourceText,12).map(x=>x[0]).filter(x=>!articleSet.has(x)).slice(0,6);}
function sourceRef(x,i){return`S${i+1}`;}
function scientificSynthesis(model,article,analysis,web,notes,focus){const topic=topTerms(article.title+' '+article.text,6).map(x=>x[0]).join(', ')||'isu utama',theory=MODELS[model],strong=web.scholar.filter(x=>x.abstract&&x.abstract!=='Tidak teridentifikasi dari data yang tersedia.').slice(0,4),litTerms=literatureTerms(web,article),refs=web.scholar.slice(0,5).map((x,i)=>`${sourceRef(x,i)} ${x.title}${x.year?' ('+x.year+')':''}`);let p1=`Pembacaan framing terhadap teks primer menunjukkan bahwa ${topic} menjadi pusat penonjolan. Dengan memakai ${theory}, hasil tersebut dibaca sebagai konstruksi makna melalui seleksi, penempatan, pengulangan, dan relasi antarbagian teks. Bukti primer tetap menjadi dasar utama; literatur web berfungsi untuk memberi bahasa konseptual dan pembanding akademik.`;
 let p2=web.scholar.length?`Penelusuran ilmiah menemukan ${web.scholar.length} karya yang relevan secara bibliografis. ${litTerms.length?`Istilah yang berulang pada judul/abstrak sumber meliputi ${litTerms.join(', ')}. `:''}${refs.length?`Sumber yang paling dekat secara istilah antara lain ${refs.slice(0,3).join('; ')}. `:''}Kedekatan ini tidak otomatis berarti karya tersebut mendukung temuan framing; dukungan substantif hanya dapat dinyatakan ketika abstrak atau teks penuh benar-benar memuat argumen yang sejalan.`:'Metadata ilmiah belum berhasil diperoleh otomatis, sehingga interpretasi ilmiah tidak boleh diperluas melampaui teori framing dan bukti teks primer.';
 let p3=strong.length?`Dari sumber yang memiliki abstrak/deskripsi, aplikasi hanya menggunakan informasi yang tersedia untuk memperkaya konteks. ${strong.slice(0,3).map((x,i)=>`[S${web.scholar.indexOf(x)+1}] memuat konteks mengenai ${topTerms(x.abstract,4).map(t=>t[0]).join(', ')||'tema yang tercantum dalam abstrak'}`).join('; ')}. Bagian ini sebaiknya diperlakukan sebagai peta literatur awal dan diverifikasi melalui pembacaan naskah penuh.`:'Sebagian besar hasil yang ditemukan hanya menyediakan metadata tanpa abstrak. Karena itu aplikasi sengaja tidak membuat ringkasan temuan artikel yang tidak tersedia.';
 let p4=notes.length?`Catatan ilmiah peneliti juga dimasukkan sebagai lapis interpretasi terpisah. Catatan tersebut dapat membantu menghubungkan fokus “${focus||'analisis framing'}” dengan bukti primer, tetapi statusnya tetap sebagai catatan peneliti dan tidak disamakan dengan hasil retrieval web.`:'Belum ada catatan ilmiah peneliti yang ditambahkan. Untuk interpretasi yang lebih spesifik, catatan membaca buku/jurnal dapat ditempel pada kolom input dan akan ditampilkan terpisah dari sumber web.';
 return{paragraphs:[p1,p2,p3,p4],refs};}
function integrateNarrative(analysis,sci,focus){return`${analysis.narrative} ${focus?`Fokus peneliti adalah “${focus}”. Karena itu pembacaan diarahkan untuk menilai bagian teks yang benar-benar berhubungan dengan fokus tersebut, sementara bagian di luar fokus tidak dipaksakan masuk ke kesimpulan. `:''}${sci.paragraphs[1]}`;}

function sourceRow(l,v){return v?`<div class="source-item"><span>${esc(l)}</span><strong>${esc(v)}</strong></div>`:'';}
function renderSource(a,q){$('sourceInfo').innerHTML=sourceRow('Judul',a.title||'(tidak terdeteksi)')+sourceRow('Domain',a.domain||'-')+sourceRow('Tanggal',a.published||'-')+sourceRow('Panjang teks',`${a.text.length.toLocaleString('id-ID')} karakter`)+sourceRow('Kalimat',q.sentences)+sourceRow('Kata terpilah',q.words);$('sourceMethod').textContent=a.method||'Input';$('sourceQuality').innerHTML=q.issues.length?`<strong>Catatan kualitas sumber</strong><ul>${q.issues.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<strong>Sumber lolos pemeriksaan dasar.</strong><span>Tidak terdeteksi pola CAPTCHA/security page atau kekurangan teks yang fatal.</span>';$('sourceQuality').className=`quality-box ${q.issues.length?'warn':'good'}`;$('sourceCard').classList.remove('hidden');}
function renderQuick(q,focus){$('evidenceScore').textContent=`Kekuatan bukti tekstual ${q.strength}/100`;$('quickGrid').innerHTML=q.items.map(([l,v])=>`<div class="quick-item"><span>${esc(l)}</span><p>${esc(v)}</p></div>`).join('');if(norm(focus)){$('focusBox').classList.remove('hidden');$('focusBox').innerHTML=`<h3>Fokus permintaan peneliti</h3><p>${esc(focus)}</p><div class="evidence-title">Bagian teks yang paling terkait</div><ul>${q.focusEvidence.length?q.focusEvidence.map(x=>`<li>${esc(short(x,330))}</li>`).join(''):'<li>Tidak ditemukan kecocokan eksplisit yang cukup kuat. Fokus tetap dipakai untuk menyusun kueri literatur, tetapi tidak dipaksakan ke bukti teks.</li>'}</ul>`;}else $('focusBox').classList.add('hidden');$('quickCard').classList.remove('hidden');}
function renderAnalysis(model,data,narrative){$('modelName').textContent=MODELS[model];$('summary').innerHTML=`<strong>Frame dominan</strong><p>${esc(data.summary)}</p>`;$('narrative').innerHTML=`<h3>Interpretasi naratif</h3><p>${esc(narrative||data.narrative)}</p>`;$('sections').innerHTML=data.sections.map(s=>`<section class="analysis-block"><h3>${esc(s.title)}</h3><p>${esc(s.interpretation)}</p><div class="evidence-title">Bukti/indikator dari teks primer</div><ul>${(s.evidence||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`).join('');$('conclusion').innerHTML=`<strong>Kesimpulan teoritis</strong><p>${esc(data.conclusion)}</p>`;$('resultCard').classList.remove('hidden');}
function academicEntry(x,i){return`<article class="result-entry"><div class="source-id">S${i+1}</div><a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${esc(x.title)}</a><div class="result-meta">${esc([x.authors,x.year,x.container].filter(Boolean).join(' · '))}</div><div class="tagline"><span class="tag">${esc(x.kind)}</span>${x.doi?`<span class="tag">DOI ${esc(x.doi)}</span>`:''}<span class="tag">relevansi ${x.score}%</span></div>${x.abstract&&x.abstract!=='Tidak teridentifikasi dari data yang tersedia.'?`<details class="abstract"><summary>Abstrak/deskripsi yang tersedia</summary><p>${esc(x.abstract)}</p></details>`:'<div class="metadata-only">Metadata saja — jangan menyimpulkan isi/temuan tanpa membaca teks penuh.</div>'}</article>`;}
function renderScientific(web,sci,notes){$('scientificCount').textContent=`${web.scholar.length} karya · ${web.books.length} buku`;$('scientificNarrative').innerHTML=sci.paragraphs.map((p,i)=>`<div class="sci-paragraph"><span>${['Pembacaan teoretis','Peta literatur','Keterbatasan inferensi','Catatan peneliti'][i]}</span><p>${esc(p)}</p></div>`).join('');$('academicResults').innerHTML=web.scholar.length?web.scholar.map(academicEntry).join(''):'<div class="empty">Belum ada karya ilmiah yang berhasil diambil otomatis.</div>';$('bookResults').innerHTML=web.books.length?web.books.map(x=>`<article class="result-entry"><a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${esc(x.title)}</a><div class="result-meta">${esc([x.authors,x.year,x.container].filter(Boolean).join(' · '))}</div><div class="tagline"><span class="tag">Buku/monograf</span><span class="tag">relevansi ${x.score}%</span></div><div class="metadata-only">Data buku digunakan sebagai jejak bibliografis; isi buku tidak diringkas tanpa teks yang tersedia.</div></article>`).join(''):'<div class="empty">Belum ada buku/monograf yang berhasil diambil otomatis.</div>';$('noteResults').innerHTML=notes.length?notes.map(n=>`<article class="result-entry note-entry"><b>${esc(n.id)} — Catatan peneliti</b><p>${esc(n.text)}</p></article>`).join(''):'<div class="empty">Tidak ada catatan ilmiah tambahan yang dimasukkan.</div>';$('scientificCard').classList.remove('hidden');}
function renderWeb(web,query){$('webQuery').textContent=query;const domains=new Set(web.news.map(x=>x.domain).filter(Boolean));$('webSummary').innerHTML=`<div class="metric"><b>${web.news.length}</b><span>berita pembanding</span></div><div class="metric"><b>${domains.size}</b><span>domain media berbeda</span></div><div class="metric"><b>${web.scholar.length}</b><span>karya ilmiah ditemukan</span></div><div class="metric"><b>${web.books.length}</b><span>buku/monograf</span></div>`;$('newsResults').innerHTML=web.news.length?web.news.map(x=>`<article class="result-entry"><a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${esc(x.title)}</a><div class="result-meta">${esc(x.domain)}${x.date?' · '+esc(x.date):''}${x.language?' · '+esc(x.language):''}</div><div class="tagline"><span class="tag">overlap ${x.score}%</span></div></article>`).join(''):'<div class="empty">Belum ada berita pembanding yang dapat diambil otomatis.</div>';$('searchLinks').innerHTML=`<a target="_blank" rel="noopener noreferrer" href="https://scholar.google.com/scholar?q=${encodeURIComponent(query)}">Google Scholar</a><a target="_blank" rel="noopener noreferrer" href="https://news.google.com/search?q=${encodeURIComponent(query)}">Google News</a><a target="_blank" rel="noopener noreferrer" href="https://search.crossref.org/?q=${encodeURIComponent(query)}">Crossref Search</a><a target="_blank" rel="noopener noreferrer" href="https://openlibrary.org/search?q=${encodeURIComponent(query)}">Open Library</a>`;$('webCard').classList.remove('hidden');return{domains:domains.size};}
function renderLimitations(article,quick,webMeta,web,q){const a=common(article),items=[];items.push({kind:'good',text:'Bukti framing pada laporan hanya diambil dari teks primer yang lolos pemeriksaan dasar; CAPTCHA/security page tidak diperlakukan sebagai berita.'});if(quick.strength<60)items.push({kind:'warn',text:'Kekuatan bukti tekstual masih terbatas. Kesimpulan sebaiknya diposisikan sebagai coding awal dan diverifikasi dengan pembacaan manual.'});else items.push({kind:'good',text:'Teks cukup untuk coding awal, tetapi makna laten, ideologi, dan motif media tetap membutuhkan interpretasi peneliti dan perbandingan sumber.'});if(!a.causes.length)items.push({kind:'warn',text:'Teks tidak menyatakan penyebab secara eksplisit; aplikasi tidak mengatribusikan sebab kepada aktor tertentu.'});if(web.errors?.length)items.push({kind:'warn',text:`Sebagian layanan eksternal gagal: ${web.errors.join(' | ')}. Kegagalan retrieval tidak diganti dengan sumber fiktif.`});if(web.scholar.length)items.push({kind:'good',text:'Sumber ilmiah diberi ID S1, S2, dan seterusnya. Ringkasan hanya menggunakan metadata/abstrak yang tersedia; metadata saja tidak dianggap sebagai bukti temuan penelitian.'});if(q.issues.length)items.push({kind:'warn',text:`Kualitas teks memiliki catatan: ${q.issues.join(' ')}`});items.push({kind:'',text:'Skor kekuatan bukti tekstual adalah indikator heuristik kelengkapan bukti, bukan reliabilitas statistik, probabilitas kebenaran, atau keputusan validitas penelitian.'});$('limitations').innerHTML=items.map(x=>`<div class="limitation ${x.kind}">${esc(x.text)}</div>`).join('');$('methodCard').classList.remove('hidden');}

function buildPlain(r){let s=`FRAMINGLAB SCIENTIFIC NARRATIVE EDITION v6.0\nModel: ${MODELS[r.model]}\nJudul: ${r.article.title||'-'}\nURL: ${r.article.url||'-'}\nFokus: ${r.focus||'-'}\n\nINTERPRETASI NARATIF\n${r.integratedNarrative}\n\nFRAME DOMINAN\n${r.analysis.summary}\n`;for(const sec of r.analysis.sections)s+=`\n${sec.title}\n${sec.interpretation}\n- ${(sec.evidence||[]).join('\n- ')}\n`;s+=`\nKESIMPULAN\n${r.analysis.conclusion}\n\nSINTESIS ILMIAH\n${r.scientific.paragraphs.join('\n\n')}\n\nSUMBER ILMIAH\n`;r.web.scholar.forEach((x,i)=>s+=`S${i+1}. ${x.title} | ${x.authors||''} | ${x.year||''} | ${x.doi||x.url}\n`);s+='\nBUKU/MONOGRAF\n';r.web.books.forEach(x=>s+=`- ${x.title} | ${x.authors||''} | ${x.year||''} | ${x.url}\n`);s+='\nBERITA PEMBANDING\n';r.web.news.forEach(x=>s+=`- ${x.title} | ${x.domain} | ${x.url}\n`);return s;}
function download(name,content,type){const b=new Blob([content],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function reportHtml(r){return`<!doctype html><html lang="id"><meta charset="utf-8"><title>Laporan FramingLab</title><style>body{font:14px Arial;max-width:940px;margin:40px auto;line-height:1.6;color:#191326}h1,h2,h3{color:#4c1d95}blockquote,.box{background:#faf5ff;border-left:4px solid #7c3aed;padding:12px 16px}li{margin:6px 0}a{color:#5b21b6}.src{margin:14px 0;padding:12px;border:1px solid #ddd;border-radius:8px}</style><h1>FramingLab — Scientific Narrative Report</h1><p><b>Model:</b> ${esc(MODELS[r.model])}<br><b>Judul:</b> ${esc(r.article.title||'-')}<br><b>URL:</b> ${esc(r.article.url||'-')}<br><b>Fokus:</b> ${esc(r.focus||'-')}</p><h2>Interpretasi naratif</h2><div class="box">${esc(r.integratedNarrative)}</div><h2>Frame dominan</h2><blockquote>${esc(r.analysis.summary)}</blockquote>${r.analysis.sections.map(s=>`<h3>${esc(s.title)}</h3><p>${esc(s.interpretation)}</p><ul>${s.evidence.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`).join('')}<h2>Kesimpulan</h2><p>${esc(r.analysis.conclusion)}</p><h2>Sintesis ilmiah</h2>${r.scientific.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}<h2>Sumber ilmiah</h2>${r.web.scholar.map((x,i)=>`<div class="src"><b>S${i+1}. <a href="${esc(x.url)}">${esc(x.title)}</a></b><br>${esc([x.authors,x.year,x.container].filter(Boolean).join(' · '))}${x.doi?'<br>DOI '+esc(x.doi):''}${x.abstract&&x.abstract!=='Tidak teridentifikasi dari data yang tersedia.'?'<p>'+esc(x.abstract)+'</p>':'<p><i>Metadata saja; teks penuh perlu dibaca sebelum mengutip temuan.</i></p>'}</div>`).join('')||'<p>Tidak tersedia.</p>'}<h2>Buku/monograf</h2><ul>${r.web.books.map(x=>`<li><a href="${esc(x.url)}">${esc(x.title)}</a> — ${esc([x.authors,x.year].filter(Boolean).join(', '))}</li>`).join('')||'<li>Tidak tersedia</li>'}</ul><h2>Berita pembanding</h2><ul>${r.web.news.map(x=>`<li><a href="${esc(x.url)}">${esc(x.title)}</a> — ${esc(x.domain)}</li>`).join('')||'<li>Tidak tersedia</li>'}</ul><p><small>FramingLab membedakan bukti teks primer, metadata/abstrak ilmiah, dan catatan peneliti. Verifikasi teks penuh tetap diperlukan untuk klaim akademik.</small></p></html>`;}

async function analyze(){clearStatus();['sourceCard','quickCard','resultCard','scientificCard','webCard','methodCard'].forEach(id=>$(id).classList.add('hidden'));const model=$('model').value,url=$('url').value.trim(),manual=$('text').value.trim(),manualTitle=$('title').value.trim(),focus=$('focus').value.trim(),notes=parseNotes($('scientificNotes').value);if(!url&&!manual){setStatus('Tempel URL atau isi artikel terlebih dahulu.','error');return;}const btn=$('analyzeBtn');btn.disabled=true;btn.textContent='MEMERIKSA SUMBER & MENELUSURI LITERATUR...';setStatus('Memvalidasi teks primer agar CAPTCHA/security page tidak dianalisis...','info');try{let article;if(manual){article=manualArticle(manual,manualTitle,url);}else{article=await readUrlWithJina(url);if(manualTitle)article.title=manualTitle;}const q=qualityCheck(article);renderSource(article,q);if(q.fatal)throw new Error(`Analisis dihentikan: ${q.issues.join(' ')} Gunakan teks artikel asli pada kolom manual.`);setStatus('Teks valid. Melakukan coding framing dan menelusuri jurnal, buku, serta berita pembanding...','info');const analysis=analyzeModel(model,article),quick=buildQuick(article,analysis,focus,q),query=buildQuery(article,focus),theoryQuery=buildTheoryQuery(model,article);renderQuick(quick,focus);const web=await webResearch(query,theoryQuery,{news:$('searchNews').checked,scholar:$('searchScholar').checked,books:$('searchBooks').checked,data:$('searchData').checked,openAlexKey:$('openAlexKey').value.trim(),maxSources:Number($('maxSources').value)||10});const sci=scientificSynthesis(model,article,analysis,web,notes,focus),integratedNarrative=integrateNarrative(analysis,sci,focus);renderAnalysis(model,analysis,integratedNarrative);renderScientific(web,sci,notes);const webMeta=renderWeb(web,query);renderLimitations(article,quick,webMeta,web,q);lastResult={version:'6.0',model,article,focus,notes,quality:q,analysis,quick,query,theoryQuery,web,scientific:sci,integratedNarrative,createdAt:new Date().toISOString()};setStatus(web.errors.length?`Analisis selesai. Sebagian layanan web tidak tersedia: ${web.errors.join(' | ')}`:'Analisis selesai. Narasi framing, landasan ilmiah, dan triangulasi konteks tersedia.',web.errors.length?'warn':'ok');$('quickCard').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){setStatus(e.message||'Analisis gagal.','error');}finally{btn.disabled=false;btn.textContent='ANALISIS NARATIF + RISET ILMIAH';}}
$('analyzeBtn').addEventListener('click',analyze);$('url').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();analyze();}});$('downloadTxtBtn').addEventListener('click',()=>lastResult&&download('hasil_framinglab_scientific.txt',buildPlain(lastResult),'text/plain;charset=utf-8'));$('downloadJsonBtn').addEventListener('click',()=>lastResult&&download('hasil_framinglab_scientific.json',JSON.stringify(lastResult,null,2),'application/json;charset=utf-8'));$('downloadHtmlBtn').addEventListener('click',()=>lastResult&&download('laporan_framinglab_scientific.html',reportHtml(lastResult),'text/html;charset=utf-8'));
